id = "perplexity"
name = "Perplexity"
version = "0.1.0"
description = "Ask questions to Perplexity AI directly from Editsync"
authors = ["Editsync Industries <support@khulnasoft.com>"]
repository = "https://github.com/khulnasoft/editsync"
schema_version = 1

[slash_commands.perplexity]
description = "Ask a question to Perplexity AI"
requires_argument = true
tooltip_text = "Ask Perplexity"
