[package]
name = "editsync_elm"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/elm.rs"
crate-type = ["cdylib"]

[dependencies]
editsync_extension_api = "0.2.0"
