[package]
name = "editsync_astro"
version = "0.1.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/astro.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
editsync_extension_api = "0.2.0"