apiVersion: batch/v1
kind: Job
metadata:
  namespace: ${EDITSYNC_KUBE_NAMESPACE}
  name: ${EDITSYNC_MIGRATE_JOB_NAME}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrator
          imagePullPolicy: Always
          image: ${EDITSYNC_IMAGE_ID}
          args:
            - migrate
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
