#!/bin/bash

set -eu
source script/lib/deploy-helpers.sh

if [[ $# != 1 ]]; then
  echo "Usage: $0 <production|staging> (postgrest not needed on preview or nightly)"
  exit 1
fi
environment=$1

export_vars_for_environment ${environment}

export EDITSYNC_DO_CERTIFICATE_ID=$(doctl compute certificate list --format ID --no-header)
export EDITSYNC_KUBE_NAMESPACE=${environment}

target_editsync_kube_cluster
envsubst < crates/collab/k8s/postgrest.template.yml | kubectl apply -f -

echo "deployed postgrest"
