id = "proto"
name = "Proto"
description = "Protocol Buffers support."
version = "0.2.1"
schema_version = 1
authors = ["Editsync Industries <support@khulnasoft.com>"]
repository = "https://github.com/khulnasoft/editsync"

[grammars.proto]
repository = "https://github.com/khulnasoft/tree-sitter-proto"
commit = "0848bd30a64be48772e15fbb9d5ba8c0cc5772ad"

[language_servers.protobuf-language-server]
name = "Protobuf Language Server"
languages = ["Proto"]
