name: Randomieditsync Tests

concurrency: randomieditsync-tests

on:
  push:
    branches:
      - randomieditsync-tests-runner
  # schedule:
  #    - cron: '0 * * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  EDITSYNC_SERVER_URL: https://editsync.khulnasoft.com

jobs:
  tests:
    name: Run randomieditsync tests
    runs-on:
      - buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Install Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "18"

      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          clean: false

      - name: Run randomieditsync tests
        run: script/randomieditsync-test-ci
