[package]
name = "derive_refineable"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/derive_refineable.rs"
proc-macro = true
doctest = false

[dependencies]
syn = "1.0.109"
quote = "1.0.38"
proc-macro2 = "1.0.93"
